experimentName: TimesNet_GECCO
trialCommand: python nni_trial.py
trialCodeDirectory: .
trialGpuNumber: 1
trialConcurrency: 1
maxTrialNumber: 10
searchSpaceFile: search_space.json
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: false
  gpuIndices: "2,3"     